### PR TITLE
Sample PR

### PR DESCRIPTION
**Pull request by muddlebee**

### CODE REVIEW

**Comment by chocos10** [comment]
can you explain this ?

**Comment by muddlebee** [comment]
@13nehu 
screenshot from 2017-03-25 00 50 38

My bad just convert the 3 commits like this as you did into one commit

**Comment by muddlebee** [comment]
Basically merge 3 commits to one. Updated https://github.com/fossiiita/githero/wiki/Challenge-2

**Comment by muddlebee** [comment]
@13nehu and a slight reminder you are yet to do the Challenge 0 complete it soon

**Pull request closed without merging**
