### PR TITLE
Completed challenge 1, navbar color, copyright alignment, footer

### PR DESCRIPTION
**Pull request by vsvipul**

### CODE REVIEW

**Comment by vsvipul** [comment]
@anweshknayak

**Comment by muddlebee** [comment]
@vsvipul555 proceed now use the hint I provided in event page on facebook

**Comment by muddlebee** [comment]
@vsvipul555 try to do some frontend issues too they are easy points for you :)

**Comment by vsvipul** [comment]
done ! changed navbar color too!

**Comment by vsvipul** [comment]
Changed alignment of copyright text !

**Comment by muddlebee** [comment]
@s 5 points for navbar button . but you have done the navbar colour before I guess

**Comment by vsvipul** [comment]
wont this pr be merged ? before it wasnt merged that is why i did it again!

**Comment by muddlebee** [comment]
@vsvipul555 no this is not to merge. please proceed to others . try the last one . let me know if any help needed in events page

**Comment by vsvipul** [comment]
okok doing !

**Comment by vsvipul** [comment]
done . added footer !

**Pull request merged**
