### PR TITLE
Completed challenge 1, changed navbar background, and rebased every commit to a single commit

### PR DESCRIPTION
**Pull request by vsvipul**

### CODE REVIEW

**Comment by muddlebee** [comment]
@vsvipul555 20 points to you. proceed to next challenge

**Comment by vsvipul** [comment]
how do i submit pr for that ? i mean after doing that, it shows nothing to commit !

**Comment by muddlebee** [comment]
@vsvipul555 try to google a bit. 
"How to merge commits into one" You will get the idea

**Comment by vsvipul** [comment]
no i merged the commits using squash but after that it shows nothing to commit ! how do i send a pr when there are no commits..?

**Comment by vsvipul** [comment]
@anweshknayak  i also changed navbar background and rebased the commits ..can u commit pls.

**Comment by muddlebee** [comment]
@vsvipul555 nice 5 points. now merge all commits present into one. rebase to 1 commit. 30 points for this.

**Comment by vsvipul** [comment]
rebased every commit into a single commit !

**Comment by muddlebee** [comment]
@vsvipul555 you added more commits too. this is not how to do. you have to every commits in your PR to one. One hint : Update your fork. then put a new PR. add some commits show to me and then merge them into one tag me again. :)

**Pull request closed without merging**
